openapi: 3.0.3
info:
  title: Search APIs
  description: "MapmyIndia Search APIs unleashes the full potential Search capabilities of MapmyIndia Maps to provide users with ultimate location discoverability experience. It helps users explore our comprehensive & accurate map with over 50 million places mapped for India & its neighbouring nations."
  termsOfService: 'http://www.mapmyindia.com/about/terms-conditions'
  version: 1.0.0
  license:
    name: MapmyIndia License Key Signup
    url: https://www.mapmyindia.com/api/signup
  contact:
    name: MapmyIndia API Support
    email: apisupport@mapmyindia.com
    url: https://www.mapmyindia.com/api/
servers:
  - url: https://apis.mapmyindia.com
    description: 'Live Prod server for Advanced Maps APIs'
paths:
  /advancedmaps/v1/{REST_KEY}/place_detail:
      get:
        tags:
          - eLoc API
        description: >-
          MapmyIndia eloc is a simple, standardized and precise pan-India digital address system. Every location has been assigned a unique digital address or an eLoc. The eLoc API can be used to extract the details of a place with the help of its eLoc i.e. a 6 digit code or a place_id.
          <p style=text-align:right><strong><a href="https://www.mapmyindia.com/api/advanced-maps/doc/sample/mapmyindia-vector-maps-place-details-api-example.php">Live Demo</a> | <a href="https://github.com/MapmyIndia/mapmyindia-rest-api/tree/master/mapmyindia-maps-place-details-api-example">Download Sample Code</a> </p>
        summary: This API returns the POI of the lat lng entered by you.
        operationId: eLocAPI
        parameters:
          - name: place_id
            in: query
            description: 'Six or Eight Digit unique code.'
            allowEmptyValue: false
            required: true
            example: "MMI000"
          - name: REST_KEY
            in: path
            description: 'The REST API licence key allocated to you by signing into our services and registering yourself as a developer.'
            allowEmptyValue: false
            required: true
            example: "threstapikeywillcomeheretoaccess"
          - name: region
            in: query
            description: 'It takes in the country code. LKA, IND, BTN, BGD, NPL for Sri-Lanka, India, Bhutan, Bangladesh, Nepal respectively. Default is India (IND)'
            allowEmptyValue: false
            example: "IND"
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/EL1'
          '204':
            description: Not found
          '400':
            description: Bad request
          '401':
            description: API access denied
          '403':
            description: Forbidden
          '500':
            description: Something went wrong
          '503':
            description: Internal server error
        deprecated: false
  /advancedmaps/v1/{REST_KEY}/rev_geocode:
      get:
        tags:
          - Reverse Geocode API
        description: >-
          Reverse Geocoding is a process to give the closest matching address to a provided geographical coordinates (latitude/longitude). MapmyIndia reverse geocoding API provides real addresses along with nearest popular landmark for any such geo-positions on the map. This API also works in Hindi language response.
          <p style=text-align:right><strong><a href="https://www.mapmyindia.com/api/advanced-maps/doc/sample/mapmyindia-vector-maps-reverse-geocoding-rest-api-example.php">Live Demo</a> | <a href="https://github.com/MapmyIndia/mapmyindia-rest-api/tree/master/mapmyindia-maps-reverse-geocoding-rest-api-example">Download Sample Code</a> </p>
        summary: This API returns the POI of the lat lng entered by you.
        operationId: ReverseGeocodeAPI
        parameters:
          - name: lat
            in: query
            description: 'The latitude of the location'
            allowEmptyValue: false
            required: true
            example: '28.569548'
          - name: lng
            in: query
            description: 'The longitude of the location'
            allowEmptyValue: false
            required: true
            example: '77.856954'
          - name: REST_KEY
            in: path
            description: 'The rest key allocated to your account.'
            allowEmptyValue: false
            required: true
            example: "threstapikeywillcomeheretoaccess"
          - name: region
            in: query
            description: 'It takes in the country code. LKA, IND, BTN, BGD, NPL for Sri-Lanka, India, Bhutan, Bangladesh, Nepal respectively. Default is India (IND)'
            allowEmptyValue: false
            example: 'IND'
          - name: lang
            in: query
            description: 'This parameter accepts the "hi" (ISO 639-1 Language Code for Hindi) as a value.'
            allowEmptyValue: false
            example: 'hi'
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/RG1'
          '204':
            description: Not found
          '400':
            description: Bad request
          '401':
            description: API access denied
          '403':
            description: Forbidden
          '500':
            description: Something went wrong
          '503':
            description: Internal server error
        deprecated: false
components:
  schemas:
    EL1:
      title: eLoc API Results
      description: The result object which contains the eLoc API results.
      type: object
      required:
        - responseCode
        - version
        - results
      properties:
        responseCode:
          type: integer
          description: This shows the response code of the results.
          format: integer
          example: 200
        version:
          type: string
          description: This shows the API version
          format: string
          example: '211.19'
        results:
          type: array
          description: The object contains the results of the reverse geocode API.
          items:
            $ref: '#/components/schemas/EL2'
    EL2:
      title: eLoc results object
      description: The result object which contains the Reverse Geocode API results.
      type: object
      required:
        - district
        - city
        - state
        - lat
        - lng
        - formatted_address
      properties:
        houseNumber:
          type: string
          description: 'House Number of the POI.'
          format: string
          example: '237'
        houseName:
          type: string
          description: 'House Name of the POI.'
          format: string
          example: 'MMI Building'
        poi:
          type: string
          description: 'Name of the POI.'
          format: string
          example: 'MapmyIndia Head Office'
        street:
          type: string
          description: 'Name of the street.'
          format: string
          example: 'Unnamed Road'
        subSubLocality:
          type: string
          description: 'Name of the subsublocality.'
          format: string
          example: ''
        subLocality:
          type: string
          description: 'Name of the sublocality.'
          format: string
          example: ''
        locality:
          type: string
          description: 'Name of the locality.'
          format: string
          example: 'Okhla industrial phase 3'
        village:
          type: string
          description: 'Name of the village.'
          format: string
          example: 'Okhla Vilage'
        subDistrict:
          type: string
          description: 'Name of the subDistrict.'
          format: string
          example: ''
        city:
          type: string
          description: 'Name of the city.'
          format: string
          example: 'New Delhi'
        state:
          type: string
          description: 'Name of the state.'
          format: string
          example: 'Delhi'
        pincode:
          type: integer
          description: 'Pincode of the location.'
          format: string
          example: '110010'
        longitude:
          type: string
          description: 'It shows us the longitude of the location searched.'
          format: double
          example: '77.092001'
        latitude:
          type: string
          description: 'It shows us the latitude of the location searched.'
          format: double
          example: '28.426335'
        type:
          type: string
          description: ''
          format: string
          example: 'POI'
        place_id:
          type: string
          description: 'Place ID of the POI.'
          format: string
          example: 'MMI000'
    RG1:
      title: Reverse Geocode API Results
      description: The result object which contains the Reverse Geocode API results.
      type: object
      required:
        - responseCode
        - version
        - results
      properties:
        responseCode:
          type: integer
          description: This shows the response code of the results.
          format: integer
          example: 200
        version:
          type: string
          description: This shows the API version
          format: string
          example: '211.19'
        results:
          type: array
          description: The object contains the results of the reverse geocode API.
          items:
            $ref: '#/components/schemas/RG2'
    RG2:
      title: Reverse geocode results object
      description: The result object which contains the Reverse Geocode API results.
      type: object
      required:
        - district
        - city
        - state
        - lat
        - lng
        - formatted_address
      properties:
        houseNumber:
          type: string
          description: 'House Number of the POI.'
          format: string
          example: '237'
        houseName:
          type: string
          description: 'House Name of the POI.'
          format: string
          example: 'MMI Building'
        poi:
          type: string
          description: 'Name of the POI.'
          format: string
          example: 'MapmyIndia Head Office'
        poi_dist:
          type: string
          description: 'The value of the poi district'
          format: string
          example: '8'
        street:
          type: string
          description: 'Name of the street.'
          format: string
          example: 'Unnamed Road'
        street_dist:
          type: string
          description: 'The value of the street district.'
          format: string
          example: '14'
        subSubLocality:
          type: string
          description: 'Name of the subsublocality.'
          format: string
          example: ''
        subLocality:
          type: string
          description: 'Name of the sublocality.'
          format: string
          example: ''
        locality:
          type: string
          description: 'Name of the locality.'
          format: string
          example: 'Okhla industrial phase 3'
        village:
          type: string
          description: 'Name of the village.'
          format: string
          example: 'Okhla Vilage'
        subDistrict:
          type: string
          description: 'Name of the subDistrict.'
          format: string
          example: ''
        city:
          type: string
          description: 'Name of the city.'
          format: string
          example: 'New Delhi'
        state:
          type: string
          description: 'Name of the state.'
          format: string
          example: 'Delhi'
        pincode:
          type: integer
          description: 'Pincode of the location.'
          format: string
          example: '110010'
        lat:
          type: string
          description: 'It shows us the latitude of the location searched.'
          format: double
          example: '28.426335'
        lng:
          type: string
          description: 'It shows us the longitude of the location searched.'
          format: double
          example: '77.092001'
        area:
          type: string
          description: 'It shows the area on which the result has been found. for eg: India, Bangladesh, etc.'
          format: string
          example: 'India'
        formatted_address:
          type: string
          description: 'This shows the formatted address of the POI.'
          format: string
          example: '237, MMI Building, MapmyIndia Head Office, Okhla industrial phase 3, Okhla Vilage, South Delhi, New Delhi, Delhi, 110010'